# Generated by Django 4.2.6 on 2023-10-17 11:54

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "event_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "register_end_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "group",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_on"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                ("cs", models.IntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rosters.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-cs"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="rosters",
            field=models.ManyToManyField(
                blank=True, related_name="rosters", to="rosters.roster"
            ),
        ),
    ]
